import type { ActiveIngredient } from "./schema";

export const ACTIVES_RAW: ActiveIngredient[] = [
  {
    id: "retinol",
    displayName: "레티놀/레티노이드",
    aliases: [
      "레티놀",
      "레티날",
      "레티놀데하이드",
      "레티닐팔미테이트",
      "retinol",
      "retinal",
      "retinaldehyde",
      "retinyl palmitate",
      "adapalene",
      "아다팔렌",
    ],
    category: "retinoid",
    photosensitive: true,
    timeOfDay: "PM",
    viscosityRank: 7,
  },
  {
    id: "aha-glycolic",
    displayName: "AHA(글라이콜릭산)",
    aliases: ["글라이콜릭애씨드", "글리콜산", "glycolic acid"],
    category: "aha",
    photosensitive: true,
    timeOfDay: "PM",
    viscosityRank: 3,
  },
  {
    id: "aha-lactic",
    displayName: "AHA(락틱산)",
    aliases: ["락틱애씨드", "젖산", "lactic acid"],
    category: "aha",
    photosensitive: true,
    timeOfDay: "PM",
    viscosityRank: 3,
  },
  {
    id: "bha-salicylic",
    displayName: "BHA(살리실산)",
    aliases: [
      "살리실릭애씨드",
      "살리실산",
      "salicylic acid",
      "BHA",
      "beta hydroxy acid",
    ],
    category: "bha",
    photosensitive: true,
    timeOfDay: "PM",
    viscosityRank: 3,
  },
  {
    id: "vitamin-c",
    displayName: "비타민C(아스코르빅)",
    aliases: [
      "아스코빅애씨드",
      "아스코르브산",
      "ascorbic acid",
      "l-ascorbic acid",
      "에틸아스코빌에텔",
      "sodium ascorbyl phosphate",
      "비타민C",
      "비타민c",
    ],
    category: "antioxidant",
    photosensitive: false,
    timeOfDay: "AM",
    viscosityRank: 4,
  },
  {
    id: "bpo",
    displayName: "벤조일퍼옥사이드",
    aliases: ["벤조일퍼옥사이드", "benzoyl peroxide", "BPO"],
    category: "antibacterial",
    photosensitive: false,
    timeOfDay: "ANY",
    viscosityRank: 6,
  },
  {
    id: "niacinamide",
    displayName: "나이아신아마이드",
    aliases: [
      "나이아신아마이드",
      "니아신아마이드",
      "niacinamide",
      "nicotinamide",
    ],
    category: "brightener",
    photosensitive: false,
    timeOfDay: "ANY",
    viscosityRank: 5,
  },
  {
    id: "peptide",
    displayName: "펩타이드",
    aliases: [
      "펩타이드",
      "peptide",
      "팔미토일펜타펩타이드",
      "copper peptide",
      "구리펩타이드",
    ],
    category: "antiaging",
    photosensitive: false,
    timeOfDay: "ANY",
    viscosityRank: 8,
  },
  {
    id: "hyaluronic-acid",
    displayName: "히알루론산",
    aliases: [
      "히알루로닉애씨드",
      "소듐하이알루로네이트",
      "hyaluronic acid",
      "sodium hyaluronate",
    ],
    category: "humectant",
    photosensitive: false,
    timeOfDay: "ANY",
    viscosityRank: 2,
  },
  {
    id: "sunscreen",
    displayName: "자외선차단",
    aliases: [
      "자외선차단",
      "선크림",
      "SPF",
      "옥토크릴렌",
      "징크옥사이드",
      "zinc oxide",
      "titanium dioxide",
      "티타늄디옥사이드",
    ],
    category: "sunscreen",
    photosensitive: false,
    timeOfDay: "AM",
    viscosityRank: 10,
  },
];
