import type { ActiveIngredient } from "./schema";

export const ACTIVES_SUPPORT: ActiveIngredient[] = [
  {
    id: "niacinamide",
    displayName: "나이아신아마이드",
    aliases: ["나이아신아마이드", "니아신아마이드", "niacinamide", "nicotinamide"],
    category: "brightener",
    photosensitive: false,
    timeOfDay: "ANY",
    viscosityRank: 5,
    groups: [],
  },
  {
    id: "azelaic-acid",
    displayName: "아젤라익산",
    aliases: ["아젤라익애씨드", "azelaic acid", "아젤라산"],
    category: "brightener",
    photosensitive: false,
    timeOfDay: "ANY",
    viscosityRank: 5,
    groups: [],
  },
  {
    id: "tranexamic-acid",
    displayName: "트라넥삼산",
    aliases: ["트라넥삼산", "tranexamic acid"],
    category: "brightener",
    photosensitive: false,
    timeOfDay: "ANY",
    viscosityRank: 5,
    groups: [],
  },
  {
    id: "arbutin",
    displayName: "알부틴",
    aliases: ["알부틴", "arbutin", "alpha-arbutin"],
    category: "brightener",
    photosensitive: false,
    timeOfDay: "ANY",
    viscosityRank: 5,
    groups: [],
  },
  {
    id: "kojic-acid",
    displayName: "코직산",
    aliases: ["코직산", "kojic acid"],
    category: "brightener",
    photosensitive: false,
    timeOfDay: "ANY",
    viscosityRank: 5,
    groups: [],
  },
  {
    id: "benzoyl-peroxide",
    displayName: "벤조일퍼옥사이드",
    aliases: ["벤조일퍼옥사이드", "benzoyl peroxide", "BPO"],
    category: "antibacterial",
    photosensitive: false,
    timeOfDay: "ANY",
    viscosityRank: 6,
    groups: [],
  },
  {
    id: "sulfur",
    displayName: "황(설퍼)",
    aliases: ["설퍼", "황", "sulfur"],
    category: "antibacterial",
    photosensitive: false,
    timeOfDay: "ANY",
    viscosityRank: 6,
    groups: ["DRYING"],
  },
  {
    id: "peptide",
    displayName: "펩타이드",
    aliases: ["펩타이드", "peptide", "팔미토일펜타펩타이드"],
    category: "antiaging",
    photosensitive: false,
    timeOfDay: "ANY",
    viscosityRank: 8,
    groups: ["PEPTIDE"],
  },
  {
    id: "copper-peptide",
    displayName: "구리펩타이드",
    aliases: ["copper peptide", "구리펩타이드", "GHK-Cu", "copper tripeptide"],
    category: "antiaging",
    photosensitive: false,
    timeOfDay: "ANY",
    viscosityRank: 8,
    groups: ["PEPTIDE"],
  },
  {
    id: "hyaluronic-acid",
    displayName: "히알루론산",
    aliases: ["히알루로닉애씨드", "소듐하이알루로네이트", "hyaluronic acid", "sodium hyaluronate"],
    category: "humectant",
    photosensitive: false,
    timeOfDay: "ANY",
    viscosityRank: 2,
    groups: ["SUPPORT"],
  },
  {
    id: "panthenol",
    displayName: "판테놀",
    aliases: ["판테놀", "panthenol", "provitamin B5", "프로비타민B5"],
    category: "humectant",
    photosensitive: false,
    timeOfDay: "ANY",
    viscosityRank: 2,
    groups: ["SUPPORT"],
  },
  {
    id: "centella",
    displayName: "센텔라",
    aliases: ["센텔라", "centella asiatica", "cica", "시카", "마데카소사이드"],
    category: "soothing",
    photosensitive: false,
    timeOfDay: "ANY",
    viscosityRank: 2,
    groups: ["SUPPORT"],
  },
  {
    id: "ceramide",
    displayName: "세라마이드",
    aliases: ["세라마이드", "ceramide", "ceramide NP", "ceramide AP"],
    category: "barrier",
    photosensitive: false,
    timeOfDay: "ANY",
    viscosityRank: 9,
    groups: ["SUPPORT"],
  },
  {
    id: "vitamin-e",
    displayName: "비타민E(토코페롤)",
    aliases: ["토코페롤", "vitamin e", "tocopherol", "비타민E"],
    category: "antioxidant",
    photosensitive: false,
    timeOfDay: "ANY",
    viscosityRank: 5,
    groups: ["SUPPORT"],
  },
  {
    id: "ferulic-acid",
    displayName: "페룰릭산",
    aliases: ["페룰릭애씨드", "ferulic acid"],
    category: "antioxidant",
    photosensitive: false,
    timeOfDay: "AM",
    viscosityRank: 4,
    groups: ["SUPPORT"],
  },
  {
    id: "sunscreen",
    displayName: "자외선차단",
    aliases: ["자외선차단", "선크림", "SPF", "옥토크릴렌", "징크옥사이드", "zinc oxide", "titanium dioxide", "티타늄디옥사이드"],
    category: "sunscreen",
    photosensitive: false,
    timeOfDay: "AM",
    viscosityRank: 10,
    groups: [],
  },
];
