import type { ActiveIngredient } from "./schema";

export const ACTIVES_RETINOIDS_ACIDS: ActiveIngredient[] = [
  {
    id: "retinol",
    displayName: "레티놀",
    aliases: ["레티놀", "retinol"],
    category: "retinoid",
    photosensitive: true,
    timeOfDay: "PM",
    viscosityRank: 7,
    groups: ["RETINOID"],
  },
  {
    id: "retinal",
    displayName: "레티날",
    aliases: ["레티날", "레티놀데하이드", "retinal", "retinaldehyde"],
    category: "retinoid",
    photosensitive: true,
    timeOfDay: "PM",
    viscosityRank: 7,
    groups: ["RETINOID"],
  },
  {
    id: "tretinoin",
    displayName: "트레티노인",
    aliases: ["트레티노인", "tretinoin", "retinoic acid", "레티노산"],
    category: "retinoid",
    photosensitive: true,
    timeOfDay: "PM",
    viscosityRank: 7,
    groups: ["RETINOID"],
  },
  {
    id: "adapalene",
    displayName: "아다팔렌",
    aliases: ["아다팔렌", "adapalene", "아다파렌"],
    category: "retinoid",
    photosensitive: true,
    timeOfDay: "PM",
    viscosityRank: 7,
    groups: ["RETINOID"],
  },
  {
    id: "retinyl-palmitate",
    displayName: "레티닐팔미테이트",
    aliases: ["레티닐팔미테이트", "retinyl palmitate"],
    category: "retinoid",
    photosensitive: true,
    timeOfDay: "PM",
    viscosityRank: 7,
    groups: ["RETINOID"],
  },
  {
    id: "hpr",
    displayName: "HPR(하이드록시피나콜론레티노에이트)",
    aliases: [
      "hydroxypinacolone retinoate",
      "HPR",
      "하이드록시피나콜론레티노에이트",
    ],
    category: "retinoid",
    photosensitive: true,
    timeOfDay: "PM",
    viscosityRank: 7,
    groups: ["RETINOID"],
  },
  {
    id: "bakuchiol",
    displayName: "바쿠치올",
    aliases: ["바쿠치올", "bakuchiol"],
    category: "retinoid_alt",
    photosensitive: false,
    timeOfDay: "ANY",
    viscosityRank: 6,
    groups: [],
  },
  {
    id: "glycolic-acid",
    displayName: "글라이콜릭산(AHA)",
    aliases: ["글라이콜릭애씨드", "글리콜산", "glycolic acid"],
    category: "aha",
    photosensitive: true,
    timeOfDay: "PM",
    viscosityRank: 3,
    groups: ["AHA"],
  },
  {
    id: "lactic-acid",
    displayName: "락틱산(AHA)",
    aliases: ["락틱애씨드", "젖산", "lactic acid"],
    category: "aha",
    photosensitive: true,
    timeOfDay: "PM",
    viscosityRank: 3,
    groups: ["AHA"],
  },
  {
    id: "mandelic-acid",
    displayName: "맨덜릭산(AHA)",
    aliases: ["맨덜릭애씨드", "맨델산", "mandelic acid"],
    category: "aha",
    photosensitive: true,
    timeOfDay: "PM",
    viscosityRank: 3,
    groups: ["AHA"],
  },
  {
    id: "salicylic-acid",
    displayName: "살리실산(BHA)",
    aliases: [
      "살리실릭애씨드",
      "살리실산",
      "salicylic acid",
      "BHA",
      "beta hydroxy acid",
    ],
    category: "bha",
    photosensitive: true,
    timeOfDay: "PM",
    viscosityRank: 3,
    groups: ["BHA"],
  },
  {
    id: "gluconolactone",
    displayName: "글루코노락톤(PHA)",
    aliases: ["글루코노락톤", "gluconolactone", "PHA"],
    category: "pha",
    photosensitive: false,
    timeOfDay: "ANY",
    viscosityRank: 3,
    groups: ["PHA"],
  },
  {
    id: "l-ascorbic-acid",
    displayName: "순수 비타민C(아스코르빅)",
    aliases: [
      "아스코빅애씨드",
      "아스코르브산",
      "ascorbic acid",
      "l-ascorbic acid",
      "비타민C",
      "비타민c",
      "vitamin-c",
      "vitamin c",
    ],
    category: "antioxidant",
    photosensitive: false,
    timeOfDay: "AM",
    viscosityRank: 4,
    groups: ["VITC_PURE", "VITC_ANTIOX"],
  },
  {
    id: "ethyl-ascorbic-acid",
    displayName: "에틸아스코르빈산(비타민C 유도체)",
    aliases: [
      "에틸아스코빌에텔",
      "ethyl ascorbic acid",
      "3-o-ethyl ascorbic acid",
    ],
    category: "antioxidant",
    photosensitive: false,
    timeOfDay: "AM",
    viscosityRank: 4,
    // BPO-tolerant stabilised derivative (not in VITC_PURE); still an antioxidant that destabilises copper peptides.
    groups: ["VITC_ANTIOX"],
  },
];
